### ISSUE TITLE
Punkt MP02

### ISSUE THREAD

**Issue by trn1ty** [jbriones95/Dumbphones#1]
# Punkt MP02

I'm submitting this without copyright; that is, the content of this GitHub issue is released freely into the Public Domain or if the relevant jurisdiction has no concept of a Public Domain, under the UNLICENSE, which may be found on-line and describes permissive sharing equivalent to the common concept of the Public Domain.

## Description

The Punkt MP02 is a product from Punkt, a company specializing in "digital minimalism". The MP-02 is marketed as a cell phone that eliminates distraction and provides just the bare necessities for communication including voice calling, SMS and MMS texting, and (after installing Punkt's GPL3-licensed app, Pigeon) Signal end-to-end-encrypted talk and text.

## Compatible bands

From [the Punkt MP02 user manual, revision 1.0 (July 2019)](https://www.punkt.ch/repofiles/17541-MP02%20Instruction%20Manual%20EN.pdf), Appendix 1.

### 3G (WCDMA)

| North American | International
| --- | ---
| B1, B2, B4, B5, B8 | B1, B5, B6, B8, B19

### 4G LTE (FDD)

| North American | International
| --- | ---
| B1, B2, B4, B5, B7, B12, B17 | B1, B3, B5, B7, B8, B19, B20

### Tools

The Punkt MP02 has the following tools:

- Alarm
- Calculator
- Phone calls
- Signal (after downloading Pigeon)
- SMS and MMS

### Notes

The Punkt MP02's USB-C port isn't PD-capable so it must be charged with a USB-A to USB-C cable rather than a USB-C to USB-C cable.

**Comment by jbriones95** [comment]
Data has been migrated. Thank you for your contribution :)
